### PR TITLE
Makes RegexManager thread-safe

### LINKED ISSUE #528: Concurrent queue locking up
We are experiencing an issue running a value through your parser where the concurrent queue (created in `RegexManager`) is locking up when attempting to retrieve a cached value from the `regularExpressionPool`. 

On our end, we are retrieving an array of objects from our backend and as we create local objects from that, we are running each phone number from the backend objects through parser. There is nothing strange or particular about the numbers it locks up on. Just "1234567890".

```
    func foo(id: [String]) async throws -> [Foo] {
        if id.isEmpty {
            return []
        }

        let response = ...
        response.errors.forEach { log.error("\($0)") }
        let foos = response.array.compactMap {
            try? Foo(responseItem: $0)
        }
        return foos
    }

  ...

    init(responseItem: Response) throws {
        do {
            if let daytimePhone = responseItem.locationContact.daytimePhone {
                let combinedPhoneComponents = daytimePhone.areaCode + daytimePhone.phoneNumber
                let phoneNumber = try PhoneNumberUtilities.shared.phoneNumberDigits(from: combinedPhoneComponents)
                self.phoneNumber = phoneNumber.string
            } else {
                self.phoneNumber = nil
            }
        } catch {
            log.error("Error: \(error)")
            self.phoneNumber = nil
        }
   }

   ...

    func phoneNumberDigits(from string: String) throws -> Int {
        let digitString = string
            .components(separatedBy: CharacterSet.decimalDigits.inverted)
            .joined()
        return Int(try pnk.parse(digitString).nationalNumber)
    }
```

When I remove the parse call and just send the string through with no validation via PNK, we have no issues. Also, after pulling down the project, I removed the `.concurrent` attribute and that seems to fix the issue as well.

### LINKED ISSUE #598: Update PhoneNumberMetadata required.
There are a lot of phone numbers added in Uzbekistan. 
The new additions are 33, 55 and 88 regional codes which are not formatted correctly.

Example +998 88 000 00 00 cannot be typed in the field.

The validation does not accept phone numbers starting with 88

### PR DESCRIPTION
**Pull request by bguidolim**
Fix #528

### CODE REVIEW

File: PhoneNumberKit/RegexManager.swift [hunk 1]
```diff
@@ -9,28 +9,26 @@
...
     public init() {
         var characterSet = CharacterSet(charactersIn: PhoneNumberConstants.nonBreakingSpace)
         characterSet.formUnion(.whitespacesAndNewlines)
-        self.spaceCharacterSet = characterSet
+        spaceCharacterSet = characterSet
     }
 
     // MARK: Regular expression pool
 
     var regularExpresionPool = [String: NSRegularExpression]()
```
Comment (michaeldwilliams) [inline PhoneNumberKit/RegexManager.swift:20]: nit: 
```suggestion
    var regularExpressionPool = [String: NSRegularExpression]()
```

File: PhoneNumberKit/RegexManager.swift [hunk 2]
```diff
@@ -9,28 +9,26 @@
...
 
     // MARK: Regular expression
 
     func regexWithPattern(_ pattern: String) throws -> NSRegularExpression {
         var cached: NSRegularExpression?
-
-        self.regularExpressionPoolQueue.sync {
-            cached = self.regularExpresionPool[pattern]
+        cached = regularExpressionPoolQueue.sync {
+            regularExpresionPool[pattern]
```
Comment (michaeldwilliams) [inline PhoneNumberKit/RegexManager.swift:31]:
```suggestion
            regularExpressionPool[pattern]
```

File: PhoneNumberKit/RegexManager.swift [hunk 3]
```diff
@@ -40,8 +38,8 @@ final class RegexManager {
         do {
             let regex = try NSRegularExpression(pattern: pattern, options: .caseInsensitive)
 
-            regularExpressionPoolQueue.async(flags: .barrier) {
-                self.regularExpresionPool[pattern] = regex
+            regularExpressionPoolQueue.sync {
+                regularExpresionPool[pattern] = regex
```
Comment (michaeldwilliams) [inline PhoneNumberKit/RegexManager.swift:42]:
```suggestion
                regularExpressionPool[pattern] = regex
```

**Review by michaeldwilliams — APPROVED** [review]
From my testing, this does appear to fix the issue. Thanks for jumping on this so quickly. HUGE help

The spelling errors are not necessary but figured since you were here, you could update them. If not, that's fine.
